entity:
  herd:
    init_random: true
    num: 25
    local_perception: 100
    local_boundary: 40
    personal_space: 50
    mass: 20.0
    min_v: 0.0
    max_v: 10.0

  shepherd:
    init_random: false
    num: 20
    local_perception: 200
    local_boundary: 30
    mass: 20.0
    min_v: 0.0
    max_v: 20.0
    configuration:
      - pose: [1400, 200]
        angle: 3.14
      - pose: [1400, 240]
        angle: 3.14
      - pose: [1400, 280]
        angle: 3.14
      - pose: [1400, 320]
        angle: 3.14
      - pose: [1400, 360]
        angle: 3.14
      - pose: [1400, 400]
        angle: 3.14
      - pose: [1400, 440]
        angle: 3.14
      - pose: [1400, 460]
        angle: 3.14
      # - pose: [1400, 420]
      #   angle: 3.14

  obstacle:
    sphere:
    # - yk: [1000, 100]
    #   Rk: 100
    # - yk: [1000, 510]
    #   Rk: 100
    # - yk: [1000, 240]
    #   Rk: 100
    # - yk: [1000, 650]
    #   Rk: 100

    hyperplane:
      # - ak: [0, 1]
      #   yk: [0, 0]
      #   boundary: [[0, 0], [1280, 10]]
      # - ak: [1, 0]
      #   yk: [0, 0]
      #   boundary: [[0, 0], [10, 720]]
      # - ak: [1, 0]
      #   yk: [1279, 0]
      #   boundary: [[1270, 0], [1280, 720]]
      # - ak: [0, 1]
      #   yk: [0, 719]
      #   boundary: [[0, 710], [1280, 720]]

  plotting:

behavior:
  math_flock:
    params:
      follow_cursor: false
      sensing_range: 40
      danger_range: 130
      initial_consensus: [800, 350]
    constants:
      c1_alpha: 3
      c1_beta: 20
      c1_gamma: 5
      c1_delta: 20

  surround:
    params:
      Cs: 25.0
      Cr: 7.0
      Cv: 2
      Co: 1
      distance_to_target: 125.0
      interagent_spacing: 150.0
      obstacle_range: 40.0
      sensing_range: 700.0

      potential_func:
        edge_follow:
          attract: True
          repulse: True
          c: 8
          m: 10
        col_avoid:
          attract: True
          repulse: True
          c: 12
          m: 10
        obs_avoid:
          attract: False
          repulse: True
          c: 6
          m: 10

