entity:
  herd:
    init_random: true
    num: 20
    local_perception: 100
    local_boundary: 40
    personal_space: 50
    mass: 20.0
    min_v: 0.0
    max_v: 10.0

  shepherd:
    init_random: false
    num: 20
    local_perception: 200
    local_boundary: 30
    mass: 20.0
    min_v: 0.0
    max_v: 3.0
    configuration:
      - pose: [1100, 200]
        angle: 3.14
      - pose: [1150, 240]
        angle: 3.14
      - pose: [1150, 280]
        angle: 3.14
      - pose: [1100, 320]
        angle: 3.14
      - pose: [1100, 380]
        angle: 3.14
      - pose: [1100, 420]
        angle: 3.14
      - pose: [1150, 460]
        angle: 3.14
      - pose: [1150, 500]
        angle: 3.14

  obstacle:
    sphere:
    # - yk: [1000, 100]
    #   Rk: 100
    # - yk: [1000, 510]
    #   Rk: 100
    # - yk: [1000, 240]
    #   Rk: 100
    # - yk: [1000, 650]
    #   Rk: 100

    hyperplane:
      - ak: [0, 1]
        yk: [0, 0]
        boundary: [[0, 0], [1280, 10]]
      - ak: [1, 0]
        yk: [0, 0]
        boundary: [[0, 0], [10, 720]]
      - ak: [-1, 0]
        yk: [1270, 0]
        boundary: [[1270, 0], [1280, 720]]
      - ak: [0, -1]
        yk: [0, 710]
        boundary: [[0, 710], [1280, 720]]

  plotting:

behavior:
  list:
    - math_flock
    - math_formation
    - orbit

  math_flock:
    interaction:
      entity:
        - herd
        - shepherd
        - obstacle
      behavior:
    params:
      follow_cursor: false
      sensing_range: 40
      danger_range: 90
      initial_consensus: [600, 350]
    constants:
      c1_alpha: 3
      c1_beta: 20
      c1_gamma: 5
      c1_delta: 20

  math_formation:
    interaction:
      entity:
        - herd
        - shepherd
        - obstacle
    params:
      sensing_range: 200
      agent_spacing: 200
      scaled_agent_spacing: 0.5