entity:
  herd:
    init_random: true
    num: 20
    x_interval: [600, 800]
    y_interval: [300, 500]
    local_perception: 100
    local_boundary: 40
    personal_space: 50
    mass: 20.0
    min_v: 0.0
    max_v: 5.0

  shepherd:
    init_random: true
    num: 9
    x_interval: [1350, 1450]
    y_interval: [200, 300]
    local_perception: 200
    local_boundary: 30
    mass: 20.0
    min_v: 0.0
    max_v: 15.0
    configuration:
      - pose: [1400, 200]
        angle: 3.14
      - pose: [1400, 240]
        angle: 3.14
      - pose: [1400, 280]
        angle: 3.14
      - pose: [1400, 320]
        angle: 3.14
      - pose: [1400, 360]
        angle: 3.14
      - pose: [1400, 400]
        angle: 3.14
      - pose: [1400, 440]
        angle: 3.14
      - pose: [1400, 460]
        angle: 3.14
      - pose: [1400, 420]
        angle: 3.14

  obstacle:
    sphere:
    # - yk: [1000, 100]
    #   Rk: 100
    # - yk: [1000, 510]
    #   Rk: 100
    # - yk: [1000, 240]
    #   Rk: 100
    # - yk: [1000, 650]
    #   Rk: 100

    hyperplane:
      # - ak: [0, 1]
      #   yk: [0, 0]
      #   boundary: [[0, 0], [1280, 10]]
      # - ak: [1, 0]
      #   yk: [0, 0]
      #   boundary: [[0, 0], [10, 720]]
      # - ak: [1, 0]
      #   yk: [1279, 0]
      #   boundary: [[1270, 0], [1280, 720]]
      # - ak: [0, 1]
      #   yk: [0, 719]
      #   boundary: [[0, 710], [1280, 720]]

  plotting:

behavior:
  math_flock:
    params:
      follow_cursor: false
      sensing_range: 40
      danger_range: 170
      initial_consensus: [800, 350]
    constants:
      c1_alpha: 3
      c1_beta: 20
      c1_gamma: 5
      c1_delta: 20

  surround:
    params:
      Cs: 1
      Cr: 0.8
      Cv: 1.5
      Co: 1
      distance_to_target: 130.0
      interagent_spacing: 140.0
      obstacle_range: 40.0
      sensing_range: 1000.0

      potential_func:
        edge_follow:
          attract: True
          repulse: True
          c: 8
          m: 2
        col_avoid:
          attract: True
          repulse: True
          c: 10
          m: 2
        obs_avoid:
          attract: False
          repulse: True
          c: 6
          m: 10
